---
- id: snykio:pypi:backports.ssl_match_hostname:40274
  title: Denial of Service (DoS)
  description: |+
    [`backports.ssl_match_hostname`][1] is a The ssl.match\_hostname()
    function from Python 3.5

    Affected versions of this package are vulnerable to Denial of Service
    attacks. Algorithmic complexity vulnerability in the ssl.match\_hostname
    function in Python 3.2.x, 3.3.x, and earlier, and unspecified versions
    of python-backports-ssl\_match\_hostname as used for older Python
    versions, allows remote attackers to cause a denial of service (CPU
    consumption) via multiple wildcard characters in the common name in a
    certificate.



    [1]: https://pypi.python.org/pypi/backports.ssl_match_hostname
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: backports.ssl_match_hostname
  vulnerable_versions:
  - "< 3.4.0.1"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-2099
  cwe:
  - CWE-399
  disclosed_date: 2013-10-09
  created_date: 2017-04-13
  last_modified_date: 2017-04-13
  credit:
  - Unknown
  references:
  - http://bugs.python.org/issue17980
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2099
  source_url: https://snyk.io/vuln/SNYK-PYTHON-BACKPORTSSSLMATCHHOSTNAME-40274
- id: victims:pypi:backports.ssl_match_hostname:2013-2099
  title: ssl.match_hostname() DoS via certificates
  affected_package: backports.ssl_match_hostname
  vulnerable_versions:
  - "<=3.2a3"
  patched_versions:
  - ">=3.4.0.1"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2013-2099
  cvss_v2_score: 2.6
  credit:
  - Victims CVE Database
  references:
  - http://bugs.python.org/issue17980
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2099
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2013/2099.yaml
