---
- id: snykio:pypi:oic:1047572
  title: Cryptographic Issues
  description: "Affected versions of this package are vulnerable to Cryptographic
    Issues\ndue to the following:\n\n1.  The IdToken signature algorithm was not checked
    automatically, but\n    only if the expected algorithm was passed in as a `kwarg`.\n2.
    \ JWA none algorithm was allowed in all flows.\n3.  `oic.consumer.Consumer.parse_authz`
    returns an unverified `IdToken`.\n    The verification of the token was left to
    the discretion of the\n    implementator.\n4.  `iat` claim was not checked for
    sanity (i.e. it could be in the\n    future)\n    ## Remediation   {#remediation}\n
    \   \n    Upgrade `oic` to version 1.2.1 or higher.\n\n"
  affected_package: oic
  vulnerable_versions:
  - "< 1.2.1"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2020-26244
  cwe:
  - CWE-310
  disclosed_date: 2020-12-01
  created_date: 2020-12-01
  last_modified_date: 2020-12-01
  credit:
  - tpazderka
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OIC-1047572
- id: snykio:pypi:oic:40768
  title: Insecure Encryption
  description: |
    [`oic`][1] is Python implementation of OAuth2 and OpenID Connect.

    Affected versions of the package are vulnerable to Insecure Encryption
    due to using a weak key derivation function and constant (initialization
    vector).



    [1]: http://pypi.python.org/pypi/oic
  affected_package: oic
  vulnerable_versions:
  - "< 0.11.0.0"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-329
  disclosed_date: 2017-05-08
  created_date: 2018-01-11
  last_modified_date: 2018-01-11
  credit:
  - Michael Schlenker
  references:
  - https://github.com/OpenIDC/pyoidc/blob/master/CHANGELOG.md#security
  - https://github.com/OpenIDC/pyoidc/commit/64665112587ef43a57cb09442dd5dd3d175f583e
  - https://github.com/OpenIDC/pyoidc/issues/349
  - https://github.com/OpenIDC/pyoidc/pull/354
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OIC-40768
