---
- id: snykio:pypi:plone.app.dexterity:1047472
  title: XML External Entity (XXE) Injection
  description: |+
    [plone.app.dexterity][1] is a Dexterity is a content type framework for
    CMF applications, with particular emphasis on Plone. It can be viewed as
    an alternative to Archetypes that is more light-weight and modular.

    Affected versions of this package are vulnerable to XML External Entity
    (XXE) Injection via `AjaxSaveHandler`.



    [1]: https://pypi.org/project/plone.app.dexterity
    \nXXE Injection is a type of attack against an application that parses XML
    input. XML is a markup language that defines a set of rules for encoding
    documents in a format that is both human-readable and machine-readable.
    By default, many XML processors allow specification of an external
    entity, a URI that is dereferenced and evaluated during XML processing.
    When an XML document is being parsed, the parser can make a request and
    include the content at the specified URI inside of the XML document.

    Attacks can include disclosing local files, which may contain sensitive
    data such as passwords or private user data, using file: schemes or
    relative paths in the system identifier.

    For example, below is a sample XML document, containing an XML element-
    username.

        <?xml version="1.0" encoding="ISO-8859-1"?>
           <username>John</username>
        </xml>
    {: .language-xml}

    An external XML entity - `xxe`, is defined using a system identifier and
    present within a DOCTYPE header. These entities can access local or
    remote content. For example the below code contains an external XML
    entity that would fetch the content of `/etc/passwd` and display it to
    the user rendered by `username`.

        <?xml version="1.0" encoding="ISO-8859-1"?>
        <!DOCTYPE foo [
           <!ENTITY xxe SYSTEM "file:///etc/passwd" >]>
           <username>&xxe;</username>
        </xml>
    {: .language-xml}

    Other XXE Injection attacks can access local resources that may not stop
    returning data, possibly impacting application availability and leading
    to Denial of Service.

  affected_package: plone.app.dexterity
  vulnerable_versions:
  - "< 2.6.8"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-611
  disclosed_date: 2020-12-01
  created_date: 2020-12-01
  last_modified_date: 2020-12-01
  credit:
  - Unknown
  references:
  - https://github.com/collective/collective.easyform/commit/261ea800fbe3bd650a83b1fe7558ba51bd7d0c9e
  - https://github.com/plone/plone.app.dexterity/commit/b11b514fb7b79301a5562a6b63150553bf6ece2d
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PLONEAPPDEXTERITY-1047472
