---
- id: ossindex:pypi:rply:360937
  title: "[CVE-2014-1604] The parser cache functionality in parsergenerator.py in
    RPLY (aka python-rply) b..."
  description: The parser cache functionality in parsergenerator.py in RPLY (aka python-rply)
    before 0.7.1 allows local users to spoof cache data by pre-creating a temporary
    rply-*.json file with a predictable name.
  affected_package: rply
  vulnerable_versions:
  - "<0.7.1"
  package_manager: pypi
  cve:
  - CVE-2014-1604
  disclosed_date: 2014-01-28
  created_date: 2014-01-28
  last_modified_date: 2017-01-15
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263
  - http://secunia.com/advisories/56429
  - http://www.openwall.com/lists/oss-security/2014/01/17/8
  - http://www.openwall.com/lists/oss-security/2014/01/18/4
  - http://www.osvdb.org/102202
  - http://xforce.iss.net/xforce/xfdb/90593
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/90593
  - https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c
  source_url: https://ossindex.net/resource/package/8401276730/vulnerabilities
- id: snykio:pypi:rply:40029
  title: Insecure use of temporary file
  description: |
    [`rply`][1] is a pure Python Lex/Yacc that works with RPython

    Affected versions of this package are vulnerable to Insecure use of
    temporary file attacks. The parser cache functionality in
    parsergenerator.py in RPLY (aka python-rply) before 0.7.1 allows local
    users to spoof cache data by pre-creating a temporary `rply-*.json` file
    with a predictable name.



    [1]: https://pypi.python.org/pypi/rply
  affected_package: rply
  vulnerable_versions:
  - "< 0.7.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2014-1604
  cwe:
  - CWE-376
  disclosed_date: 2014-01-14
  created_date: 2014-01-14
  last_modified_date: 2014-01-14
  credit:
  - Unknown
  references:
  - http://www.openwall.com/lists/oss-security/2014/01/17/8
  - https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c
  source_url: https://snyk.io/vuln/SNYK-PYTHON-RPLY-40029
- id: snykio:pypi:rply:559862
  title: Denial of Service (DoS)
  description: |+
    [rply][1] is a Python parser generator, that also works with RPython.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS). The package creates temporary files insecurely. This could be
    abused by an attacker to conduct denial of service attacks.



    [1]: https://rply.readthedocs.io/
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: rply
  vulnerable_versions:
  - "< 0.7.4"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2014-1938
  cwe:
  - CWE-400
  disclosed_date: 2020-03-12
  created_date: 2019-11-21
  last_modified_date: 2019-11-21
  credit:
  - Unknown
  references:
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737627
  source_url: https://snyk.io/vuln/SNYK-PYTHON-RPLY-559862
- id: victims:pypi:rply:2014-1604
  title: 'rply: insecure temporary file creation'
  description: 'rply stores its cache files in /tmp. This is insecure because /tmp
    is world-writable, and the file names rply uses are predicatable.

'
  affected_package: rply
  vulnerable_versions:
  - "<=0.7.0"
  patched_versions:
  - ">=0.7.1"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2014-1604
  cvss_v2_score: 2.1
  credit:
  - Victims CVE Database
  references:
  - http://www.openwall.com/lists/oss-security/2014/01/17/8
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263
  - https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/1604.yaml
